# Generated by Django 5.2.8 on 2025-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqfeedback',
            options={},
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='is_useful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
