# Generated by Django 5.2.6 on 2025-10-10 06:02
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [("tickets", "0003_attachment_comment")]
    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-10-10 00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
