# Generated by Django 5.2.6 on 2025-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticketlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/'),
        ),
    ]
