# Generated by Django 5.2.8 on 2025-12-07 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faqfeedback',
            unique_together={('faq', 'user')},
        ),
    ]
