# Generated by Django 5.2.6 on 2025-10-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='frt_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolve_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
