# Generated by Django 5.2.8 on 2025-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_merge_0012_ticket_asset_faq_and_logs_0013_alter_ticket_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20),
        ),
    ]
